# Generated by Django 4.2.29 on 2026-03-08 00:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_user_review_author'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='review',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='{ self.title.replace(" ", "-").lower() }', max_length=200, unique_for_date='published_at'),
        ),
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
