# Generated by Django 4.2.29 on 2026-03-08 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_managers_review_slug_alter_review_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slug',
            field=models.SlugField(default='titulo', max_length=200, unique_for_date='published_at'),
        ),
    ]
