# Generated by Django 4.2.29 on 2026-03-08 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='slug',
            new_name='slugfied_title',
        ),
    ]
