# Generated by Django 4.2.29 on 2026-03-08 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_alter_review_slugfied_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='slugfied_title',
            field=models.SlugField(blank=True, default='', max_length=200, unique_for_date='published_at'),
        ),
    ]
